import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {abi} from 'genlayer-js';
import {RecoveryStore,recoveryKey,validateRecovered,type RecoveryRecord,type StorageLike} from '../src/recovery';
import {ReadScheduler,ReadFailure,retryDelay,installReadScheduler,classifyReadError,visible} from '../src/read-scheduler';
import {WalletSession,type Provider} from '../src/wallet';
import {WriteController,type Prepared,type Draft} from '../src/controller';
import {createReadAdapter} from '../src/genlayer';
import {config,normalizePack,identifiers} from '../src/core';
import type {TxOutcome} from '../src/transactions';
const a=JSON.parse(fs.readFileSync(new URL('fixtures/synthetic.json',import.meta.url),'utf8'));
const tx='0x'+'b'.repeat(64) as `0x${string}`;
const p:Prepared={client_key:a.client_key,claim:a.claim,context:a.context,urls:a.urls,creator:a.creator,request_id:a.request_id,payload_digest:a.payload_digest,contract:config.contract};
const draft:Draft={client_key:p.client_key,claim:p.claim,context:p.context,urls:p.urls};
class Memory implements StorageLike {data=new Map<string,string>();getItem(k:string){return this.data.get(k)??null}setItem(k:string,v:string){this.data.set(k,v)}}
function active(state:NonNullable<RecoveryRecord['active']>['lastState']='pending',id:string|undefined=tx,phase:NonNullable<RecoveryRecord['active']>['phase']='tracking'){return {prepared:structuredClone(p),tx:id,submittedAt:1000,lastState:state,phase}}
function receipt(status='FINALIZED'):TxOutcome{return {status,consensus:'MAJORITY_AGREE',execution:'SUCCESS',returns:[{request_id:p.request_id,disposition:'NEW',result_status:'PARTIAL'}],raw:{hash:tx,sender:p.creator,recipient:config.contract,data:{calldata:{base64:Buffer.from(abi.calldata.encode(abi.calldata.makeCalldataObject('assess',[p.client_key,p.claim,p.context,p.urls]))).toString('base64')}}}}}
function setup(options:{lag?:number;lookup?:'missing'|'match'|'conflict';outcomes?:TxOutcome[];error?:Error;foreground?:()=>Promise<void>;pause?:()=>Promise<void>}={}){
 const storage=new Memory(),store=new RecoveryStore(storage),wallet=new WalletSession();let writes=0,reads=0,lookups=0,receipts=0;const routes:string[]=[],delays:number[]=[];
 const c=new WriteController(wallet,()=>{}, {async getProtocolInfo(){return {}},async lookupRequest(){lookups++;return options.lookup==='match'||options.lookup==='conflict'?{found:true,request_id:p.request_id,payload_digest:options.lookup==='conflict'?'f'.repeat(64):p.payload_digest,result_status:'PARTIAL'}:{found:false,request_id:p.request_id}},async getAssessment(){reads++;return options.lag&&reads<=options.lag?{found:false}:{found:true,assessment:a}}},()=>({async assess(){writes++;return tx},async getTransaction(){return receipt()}}),async ms=>{delays.push(ms??5000);await options.pause?.()},id=>routes.push(id),{store,foreground:options.foreground??(async()=>{}),receipt:{async getTransaction(id){receipts++;assert.equal(id,tx);if(options.error)throw options.error;return options.outcomes?.[receipts-1]??receipt()}}});
 return {c,store,storage,wallet,routes,delays,get writes(){return writes},get reads(){return reads},get lookups(){return lookups},get receipts(){return receipts}};
}
test('draft and client_key survive refresh without regeneration',()=>{const m=new Memory(),s=new RecoveryStore(m);s.save(draft);const reloaded=new RecoveryStore(m).load()!;assert.equal(reloaded.draft.client_key,p.client_key);assert.deepEqual(reloaded.draft,draft);assert.equal(reloaded.active,undefined)});
test('recovery store persists only coordinates/input, never Assessment, receipt or wallet secrets',()=>{const m=new Memory(),s=new RecoveryStore(m);s.save({...draft,seed:'secret'} as any,{...active(),wallet:{id:'test',name:'OKX Wallet',privateKey:'secret'} as any,assessment:a,signature:'secret'} as any);const raw=m.getItem(recoveryKey)!;assert.doesNotMatch(raw,/secret|signature|assessment|pairs/);assert.equal(new RecoveryStore(m).load()!.active!.tx,tx)});
for(const state of ['submitted','pending','accepted_waiting_finality','finalized_reading','tracking_unavailable'] as const)test(`refresh ${state} resumes same tx before lookup and never writes`,async()=>{const x=setup();x.store.save(draft,active(state));const loaded=new RecoveryStore(x.storage).load()!;await x.c.recover(loaded.active!);assert.equal(x.receipts,1);assert.equal(x.lookups,0);assert.equal(x.writes,0);assert.equal(x.c.snapshot.prepared!.client_key,p.client_key);assert.equal(x.c.snapshot.state,'finalized_partial');assert.deepEqual(x.routes,[p.request_id])});
test('unknown submission with matching finalized lookup recovers without receipt or write',async()=>{const x=setup({lookup:'match'});await x.c.recover({...active('awaiting_signature'),tx:undefined,phase:'submission_unknown'});assert.equal(x.receipts,0);assert.equal(x.writes,0);assert.equal(x.lookups,1);assert.deepEqual(x.routes,[p.request_id])});
test('unknown found=false retains key and locks all submission/new-assessment paths',async()=>{const x=setup();await x.c.recover({...active('awaiting_signature'),tx:undefined,phase:'submission_unknown'});assert.equal(x.c.snapshot.readIssue,'SUBMISSION_UNKNOWN');assert.equal(x.c.snapshot.state,'tracking_unavailable');assert.equal(x.c.canStartNew,false);assert.throws(()=>x.c.newAssessment());await x.c.submit(draft);await x.c.resume();assert.equal(x.writes,0);assert.equal(x.lookups,2);assert.equal(x.c.snapshot.prepared!.client_key,p.client_key)});
test('unknown lookup conflict cannot recover someone else/different payload',async()=>{const x=setup({lookup:'conflict'});await x.c.recover({...active(),tx:undefined,phase:'submission_unknown'});assert.equal(x.c.snapshot.error?.code,'IDEMPOTENCY_CONFLICT');assert.equal(x.writes,0);assert.equal(x.reads,0)});
test('completed refresh rechecks actual receipt once, wallet-free, without cached success',async()=>{const x=setup();await x.c.recover(active('finalized_partial',tx,'completed'));assert.equal(x.receipts,1);assert.equal(x.reads,1);assert.equal(x.wallet.account,undefined);assert.equal(x.writes,0);assert.equal(x.store.load()!.active!.phase,'completed')});
test('finalized read lag keeps coordinates; Resume retries getter only after confirmation',async()=>{const x=setup({lag:6});await x.c.recover(active('finalized_reading'));assert.equal(x.c.snapshot.readIssue,'FINALIZED_READ_LAG');assert.equal(x.c.snapshot.state,'tracking_unavailable');assert.equal(x.store.load()!.active!.tx,tx);await x.c.resume();assert.equal(x.receipts,1);assert.equal(x.reads,7);assert.equal(x.writes,0);assert.equal(x.c.snapshot.state,'finalized_partial')});
test('Accepted is not success across refresh; finality and matching read still required',async()=>{const x=setup({outcomes:[receipt('ACCEPTED'),receipt()]});await x.c.recover(active('accepted_waiting_finality'));assert.equal(x.receipts,2);assert.equal(x.reads,1);assert.deepEqual(x.delays,[5000]);assert.equal(x.c.snapshot.state,'finalized_partial')});
test('one controller/poller: concurrent resume and recovery do not duplicate receipt reads',async()=>{let release!:()=>void,entered!:()=>void;const waiting=new Promise<void>(r=>release=r),start=new Promise<void>(r=>entered=r);const x=setup({foreground:async()=>{entered();await waiting}});const task=x.c.recover(active());await start;await x.c.resume();await x.c.recover(active());assert.equal(x.receipts,0);release();await task;assert.equal(x.receipts,1);assert.equal(x.writes,0)});
test('hidden tab blocks polling and becomes visible without compensation burst',async()=>{let release!:()=>void,entered!:()=>void;const pause=new Promise<void>(r=>release=r),start=new Promise<void>(r=>entered=r);const x=setup({foreground:async()=>{entered();await pause}});const task=x.c.recover(active());await start;assert.equal(x.receipts,0);release();await task;assert.equal(x.receipts,1);assert.equal(x.writes,0)});
test('visibility helper removes listener after foreground resumes',async()=>{const doc=Object.assign(new EventTarget(),{hidden:true});const old=(globalThis as any).document;(globalThis as any).document=doc;try{let done=false;const task=visible().then(()=>done=true);await Promise.resolve();assert.equal(done,false);doc.hidden=false;doc.dispatchEvent(new Event('visibilitychange'));await task;assert.equal(done,true)}finally{if(old===undefined)delete (globalThis as any).document;else(globalThis as any).document=old}});
test('long pending uses 5/10/15s bounded schedule and stops with tx retained',async()=>{const x=setup({outcomes:Array.from({length:120},()=>receipt('PENDING'))});await x.c.recover(active());assert.equal(x.receipts,120);assert.deepEqual([...new Set(x.delays)],[5000,10000,15000]);assert.equal(x.c.snapshot.readIssue,'TRACKING_UNAVAILABLE');assert.equal(x.c.snapshot.tx,tx);assert.equal(x.writes,0);assert.equal(x.c.canStartNew,false)});
for(const issue of ['RATE_LIMITED','RPC_TEMPORARY_FAILURE','RPC_UNAVAILABLE'] as const)test(`${issue} is tracking/read failure, not execution failure`,async()=>{const x=setup({error:new ReadFailure(issue,'Injected read failure')});await x.c.recover(active());assert.equal(x.c.snapshot.state,'tracking_unavailable');assert.equal(x.c.snapshot.readIssue,issue);assert.equal(x.c.snapshot.tx,tx);assert.equal(x.writes,0)});
test('actual terminal execution failure retains evidence and permits explicit New only',async()=>{const failed={...receipt(),execution:'ERROR' as const};const x=setup({outcomes:[failed]});await x.c.recover(active());assert.equal(x.c.snapshot.state,'execution_failed');assert.equal(x.store.load()!.active!.phase,'terminal_failed');assert.equal(x.writes,0);assert.equal(x.c.canStartNew,true);assert.notEqual(x.c.newAssessment(),p.client_key)});
test('tampered recovery input/hash cannot trigger network or write',async()=>{const x=setup(),bad=active();bad.prepared.claim='different';await x.c.recover(bad);assert.equal(x.receipts,0);assert.equal(x.reads,0);assert.equal(x.writes,0);assert.equal(x.c.locked,true);assert.equal(x.c.snapshot.error?.code,'REQUEST_ID_MISMATCH');assert.equal(x.c.snapshot.readIssue,undefined);await assert.rejects(()=>validateRecovered(bad.prepared))});
test('wrong network/version/corrupt storage never silently switches target or overwrites evidence',()=>{const m=new Memory(),s=new RecoveryStore(m);s.save(draft,active());const raw=m.getItem(recoveryKey)!,x=JSON.parse(raw);x.chainId=1;m.setItem(recoveryKey,JSON.stringify(x));assert.equal(s.load(),undefined);assert.equal(s.problem,'INVALID_RECOVERY_STATE');s.save(draft);assert.equal(JSON.parse(m.getItem(recoveryKey)!).chainId,1);assert.equal(new RecoveryStore({getItem(){return '{broken'},setItem(){}}).load(),undefined)});
test('unavailable or quota-denied storage explicitly reports lack of refresh recovery',()=>{const s=new RecoveryStore(undefined);assert.equal(s.available,false);const blocked=new RecoveryStore({getItem(){throw Error('blocked')},setItem(){}});assert.equal(blocked.load(),undefined);assert.equal(blocked.available,false);assert.equal(blocked.problem,'STORAGE_UNAVAILABLE');const q=new RecoveryStore({getItem(){return null},setItem(){throw Error('quota')}});q.save(draft,active());assert.equal(q.available,false);assert.equal(q.problem,'STORAGE_UNAVAILABLE')});
test('wallet disconnect/account change after submission leaves original read identity intact',async()=>{const x=setup();let account='0x'+'2'.repeat(40);const provider:Provider={request:async({method})=>method==='eth_chainId'?'0xf22f':[account]};await x.wallet.connect({id:'other',name:'Other wallet',provider});x.wallet.disconnect();account='0x'+'3'.repeat(40);await x.wallet.connect({id:'new',name:'Other wallet',provider});await x.c.recover(active());assert.equal(x.c.snapshot.prepared!.creator,p.creator);assert.notEqual(x.wallet.account,p.creator);assert.equal(x.writes,0);assert.equal(x.c.snapshot.state,'finalized_partial')});
test('signature boundary persisted before wallet invocation; lost response recovers conservatively',async()=>{const m=new Memory(),s=new RecoveryStore(m),w=new WalletSession();const provider:Provider={request:async({method})=>method==='eth_chainId'?'0xf22f':[p.creator]};await w.connect({id:'wallet',name:'MetaMask',provider});let writes=0;
 const c=new WriteController(w,()=>{}, {async getProtocolInfo(){return {}},async lookupRequest(){return {found:false,request_id:p.request_id}},async getAssessment(){return {found:false}}},()=>({async assess(){writes++;assert.equal(s.load()!.active!.phase,'submission_unknown');assert.equal(s.load()!.active!.prepared.request_id,p.request_id);throw Error('response lost')},async getTransaction(){throw Error('No tx ID')}}),async()=>{},()=>{}, {store:s});await c.submit(draft);assert.equal(writes,1);assert.equal(c.snapshot.readIssue,'SUBMISSION_UNKNOWN');await c.submit(draft);assert.equal(writes,1);assert.throws(()=>c.newAssessment());assert.equal(s.load()!.active!.prepared.client_key,p.client_key)});
function clock(){let time=0;const sleeps:number[]=[];return {get time(){return time},sleeps,now:()=>time,sleep:async(ms:number)=>{sleeps.push(ms);time+=ms}}}
test('Retry-After seconds/date and reset header correctly determine delay',()=>{assert.equal(retryDelay(new Headers({'Retry-After':'12'}),0),12000);assert.equal(retryDelay(new Headers({'Retry-After':new Date(20000).toUTCString()}),0),20000);assert.equal(retryDelay(new Headers({'X-Ratelimit-Reset':'10'}),0),10000);assert.equal(retryDelay(new Headers({'Retry-After':'bad'}),0),0);assert.equal(retryDelay(new Headers({'Retry-After':'bad','X-Ratelimit-Reset':'45'}),0),45000)});
test('429 Retry-After respected; consecutive limits increase shared cooldown and success resets streak',async()=>{const t=clock(),s=new ReadScheduler(t.now,t.sleep,async()=>{});let n=0;await s.run('read',async()=>{if(n++<2)throw new ReadFailure('RATE_LIMITED','429',12000);return 'ok'});assert.deepEqual(t.sleeps,[12000,20000]);let first=true;await s.run('next',async()=>{if(first){first=false;throw new ReadFailure('RATE_LIMITED','429')}return 'ok'});assert.equal(t.sleeps.at(-1),10000)});
test('shared cooldown serializes protocol/receipt/report; duplicates coalesce across rerenders',async()=>{const t=clock(),s=new ReadScheduler(t.now,t.sleep,async()=>{});let calls=0,active=0,max=0;const times:number[]=[];const read=async()=>{max=Math.max(max,++active);times.push(t.time);calls++;active--;if(calls===1)throw new ReadFailure('RATE_LIMITED','429',15000);return 'ok'};const a=s.run('protocol',read),b=s.run('receipt',read),c=s.run('report',read),d=s.run('report',read);assert.equal(c,d);await Promise.all([a,b,c,d]);assert.equal(max,1);assert.deepEqual(times,[0,15000,15000,15000]);assert.equal(calls,4)});
test('429 read budget is finite and next read obeys outstanding shared cooldown',async()=>{const t=clock(),s=new ReadScheduler(t.now,t.sleep,async()=>{});let calls=0;await assert.rejects(()=>s.run('limited',async()=>{calls++;throw new ReadFailure('RATE_LIMITED','429')}));assert.equal(calls,3);const until=s.cooldownUntil;await s.run('after-rerender',async()=>{assert.ok(t.time>=until);return true});assert.deepEqual(t.sleeps,[10000,20000,40000])});
test('temporary/offline errors are classified, retries remain finite and read-only',async()=>{const t=clock(),s=new ReadScheduler(t.now,t.sleep,async()=>{});let n=0;await s.run('transient',async()=>{if(n++<2)throw Error('connection reset');return true});assert.deepEqual(t.sleeps,[5000,10000]);let offline=0;await assert.rejects(()=>s.run('offline',async()=>{offline++;throw new ReadFailure('RPC_UNAVAILABLE','offline')}));assert.equal(offline,1);assert.equal(classifyReadError({cause:{status:429}}).issue,'RATE_LIMITED')});
test('RPC HTTP shim handles real Response headers/body and never retries write methods',async()=>{const t=clock(),s=new ReadScheduler(t.now,t.sleep,async()=>{});let reads=0,writes=0;const target={fetch:async(_input:any,init:any)=>{const q=JSON.parse(init.body);if(q.method==='eth_sendRawTransaction'){writes++;return new Response('no',{status:429})}reads++;return reads===1?new Response('limited',{status:429,headers:{'Retry-After':'18'}}):Response.json({result:{found:false}})}};const clean=installReadScheduler(target as any,s);try{const response=await target.fetch(config.rpc,{body:JSON.stringify({method:'gen_call',params:[]})});assert.deepEqual(await response.json(),{result:{found:false}});assert.equal(reads,2);assert.deepEqual(t.sleeps,[18000]);assert.equal((await target.fetch(config.rpc,{body:JSON.stringify({method:'eth_sendRawTransaction'})})).status,429);assert.equal(writes,1)}finally{clean()}});
test('RPC envelope rate limit uses shared cooldown, not generic model/write retry',async()=>{const t=clock(),s=new ReadScheduler(t.now,t.sleep,async()=>{});let n=0;const target={fetch:async()=>Response.json(n++===0?{error:{code:-32005,message:'limit'}}:{result:'ok'})};const clean=installReadScheduler(target as any,s);try{await target.fetch(config.rpc,{body:JSON.stringify({method:'eth_getTransactionByHash',params:[tx]})} as any);assert.deepEqual(t.sleeps,[10000]);assert.equal(n,2)}finally{clean()}});
test('failed protocol cache resets for explicit read retry; incompatible protocol remains guarded',async()=>{let calls=0;const protocol={protocol_version:config.protocolVersion,schema_version:config.schemaVersion,relation_rules:config.rulesIdentifier,limits:config.limits,source_rules:config.sourceRules};const r=createReadAdapter({async readContract(){if(calls++===0)throw new ReadFailure('RATE_LIMITED','429');return protocol}});await assert.rejects(()=>r.getProtocolInfo(),(e:any)=>e.readIssue==='RATE_LIMITED');assert.deepEqual(await r.getProtocolInfo(),protocol);assert.equal(calls,2)});
test('installing read shim twice cannot create nested schedulers or retries',async()=>{const t=clock(),s=new ReadScheduler(t.now,t.sleep,async()=>{});let n=0;const target={fetch:async()=>{n++;return Response.json({result:true})}};const first=installReadScheduler(target as any,s),wrapped=target.fetch,second=installReadScheduler(target as any,s);assert.equal(target.fetch,wrapped);try{await target.fetch(config.rpc,{body:JSON.stringify({method:'gen_call',params:[]})} as any);assert.equal(n,1)}finally{second();first()}});
test('preflight RPC failure is a read pause; Resume can recheck without sending assess',async()=>{const w=new WalletSession();await w.connect({id:'mock',name:'Injected',provider:{request:async({method})=>method==='eth_chainId'?'0xf22f':[p.creator]}});let lookups=0,writes=0;const c=new WriteController(w,()=>{}, {async getProtocolInfo(){return {}},async lookupRequest(){if(lookups++===0)throw new ReadFailure('RPC_TEMPORARY_FAILURE','offline');return {found:false,request_id:p.request_id}},async getAssessment(){return {found:false}}},()=>({async assess(){writes++;return tx},async getTransaction(){return receipt()}}),async()=>{},()=>{});await c.submit(draft);assert.equal(c.snapshot.state,'tracking_unavailable');assert.equal(c.snapshot.readIssue,'RPC_TEMPORARY_FAILURE');assert.equal(c.locked,false);await c.resume();assert.equal(c.snapshot.state,'idle');assert.equal(writes,0)});
test('recovery draft/active mismatch is rejected rather than altering request namespace',()=>{const m=new Memory(),s=new RecoveryStore(m);s.save(draft,active());const value=JSON.parse(m.getItem(recoveryKey)!);value.draft.client_key='different';m.setItem(recoveryKey,JSON.stringify(value));assert.equal(s.load(),undefined);assert.equal(s.problem,'INVALID_RECOVERY_STATE')});
test('storage warning copy and unknown/read-lag classifications are bilingual',async()=>{const {copy}=await import('../src/i18n');for(const key of ['RATE_LIMITED','RPC_TEMPORARY_FAILURE','RPC_UNAVAILABLE','FINALIZED_READ_LAG','SUBMISSION_UNKNOWN','storageUnavailable','invalidRecovery'] as const){assert.ok(copy.en[key]);assert.ok(copy.zh[key])}assert.match(copy.en.SUBMISSION_UNKNOWN,/does not prove failure/);assert.match(copy.en.FINALIZED_READ_LAG,/Finalized transaction confirmed/)});
test('incomplete/invalid editable draft survives refresh but canonical input checks remain separate',()=>{const m=new Memory(),s=new RecoveryStore(m);const d={...draft,claim:'x'.repeat(601),urls:['incomplete', 'https://example.com/'+ 'x'.repeat(513)]};s.save(d);assert.deepEqual(s.load()!.draft,d);assert.equal(s.problem,undefined)});
test('known signature rejection clears ambiguity while preserving original key and sends nothing automatically',async()=>{const m=new Memory(),s=new RecoveryStore(m),w=new WalletSession();await w.connect({id:'mock',name:'Injected',provider:{request:async({method})=>method==='eth_chainId'?'0xf22f':[p.creator]}});let attempted=0;const c=new WriteController(w,()=>{}, {async getProtocolInfo(){return {}},async lookupRequest(){return {found:false,request_id:p.request_id}},async getAssessment(){return {found:false}}},()=>({async assess(){attempted++;throw {code:4001}},async getTransaction(){throw Error('No transaction')}}),async()=>{},()=>{}, {store:s});await c.submit(draft);assert.equal(attempted,1);assert.equal(c.snapshot.state,'rejected_by_user');assert.equal(s.load()!.active,undefined);assert.equal(s.load()!.draft.client_key,p.client_key);assert.equal(c.locked,false)});
test('preflight idempotency conflict has no submission ambiguity and allows explicit New key',async()=>{const x=setup({lookup:'conflict'});await x.wallet.connect({id:'mock',name:'Injected',provider:{request:async({method})=>method==='eth_chainId'?'0xf22f':[p.creator]}});await x.c.submit(draft);assert.equal(x.c.snapshot.error?.code,'IDEMPOTENCY_CONFLICT');assert.equal(x.writes,0);assert.equal(x.c.canStartNew,true);assert.notEqual(x.c.newAssessment(),p.client_key)});

test('saved completed hint cannot bypass unavailable actual receipt/finality',async()=>{const x=setup({error:new ReadFailure('RPC_UNAVAILABLE','No receipt')});await x.c.recover(active('finalized_partial',tx,'completed'));assert.equal(x.c.snapshot.state,'tracking_unavailable');assert.equal(x.reads,0);assert.equal(x.routes.length,0);assert.equal(x.writes,0)});

test('single-pass normalized BOM text stays byte-identical across persistence/hash recovery',async()=>{const payload=normalizePack('\uFEFF\uFEFFclaim',' \uFEFFcontext ',p.urls);const prepared={...p,...payload,...await identifiers(p.creator,p.client_key,payload)};assert.equal(prepared.claim,'\uFEFFclaim');assert.equal(prepared.context,'\uFEFFcontext');const m=new Memory(),s=new RecoveryStore(m);s.save(prepared,{...active(),prepared});assert.equal(s.load()!.active!.prepared.claim,prepared.claim);const restored=await validateRecovered(s.load()!.active!.prepared);assert.equal(restored.claim,prepared.claim);assert.equal(restored.context,prepared.context);assert.equal(restored.payload_digest,prepared.payload_digest)});
