import test from 'node:test';
import assert from 'node:assert/strict';
import {createElement} from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {discoverWallets,WalletSession,type WalletChoice,type Provider} from '../src/wallet';
import {WalletPanel,connectDiscovered} from '../src/WalletPanel';
import {copy} from '../src/i18n';
function provider(flags:Partial<Provider>={}):Provider{return {...flags,request:async({method})=>method==='eth_chainId'?'0xf22f':['0x'+'1'.repeat(40)]}}
function discovery(list:{provider:Provider;rdns:string;uuid:string;name:string}[]=[],legacy:object={}){const target=Object.assign(new EventTarget(),legacy);let found:WalletChoice[]=[];target.addEventListener('eip6963:requestProvider',()=>{for(const x of list)announce(x)});function announce(x:typeof list[number]){target.dispatchEvent(new CustomEvent('eip6963:announceProvider',{detail:{provider:x.provider,info:{rdns:x.rdns,uuid:x.uuid,name:x.name}}}))}const clean=discoverWallets(target as unknown as Window,x=>found=x);return {get found(){return found},announce,clean}}
const mm=(p=provider())=>({provider:p,rdns:'io.metamask',uuid:'mm',name:'MetaMask'});
const okx=(p=provider())=>({provider:p,rdns:'com.okx.wallet',uuid:'okx',name:'OKX Wallet'});
test('zero providers publishes empty list and generic install guidance',()=>{const d=discovery();assert.deepEqual(d.found,[]);const html=renderToStaticMarkup(createElement(WalletPanel,{choices:d.found,wallet:new WalletSession(),onConnect:()=>{},onDisconnect:()=>{},disabled:false,text:copy.en}));assert.match(html,/No compatible browser wallet detected/);assert.match(html,/Install or enable an EVM-compatible browser wallet/);assert.doesNotMatch(html,/<select/);d.clean()});
test('one announced provider connects exact choice only on user action',()=>{const d=discovery([mm()]);let chosen:WalletChoice|undefined;assert.equal(chosen,undefined);connectDiscovered(d.found,x=>chosen=x,()=>assert.fail());assert.equal(chosen,d.found[0]);d.clean()});
test('multiple announced MetaMask and OKX providers open chooser without connecting',()=>{const d=discovery([mm(),okx()]);let opened=0;connectDiscovered(d.found,()=>assert.fail(),()=>opened++);assert.equal(opened,1);assert.deepEqual(d.found.map(x=>x.name),['MetaMask','OKX Wallet']);d.clean()});
test('unknown compatible EIP6963 provider appears with installed brands',()=>{const d=discovery([mm(),okx(),{provider:provider(),rdns:'io.rabby',uuid:'rabby',name:'Rabby'}]);assert.deepEqual(d.found.map(x=>x.name),['MetaMask','OKX Wallet','Rabby']);d.clean()});
test('EIP6963 and same legacy provider deduplicate',()=>{const p=provider({isOkxWallet:true});const d=discovery([okx(p)],{ethereum:p,okxwallet:p});assert.equal(d.found.length,1);assert.equal(d.found[0].provider,p);d.clean()});
test('OKX announced and distinct legacy wrapper deduplicate by wallet family',()=>{const p=provider(),legacy=provider({isOkxWallet:true});const d=discovery([okx(p)],{ethereum:legacy,okxwallet:legacy});assert.equal(d.found.length,1);assert.equal(d.found[0].provider,p);assert.equal(d.found[0].name,'OKX Wallet');d.clean()});
test('legacy window.ethereum supports unknown EIP1193 wallet',()=>{const p=provider();const d=discovery([],{ethereum:p});assert.equal(d.found.length,1);assert.equal(d.found[0].provider,p);d.clean()});
test('legacy aggregate is not a wallet when explicit provider list exists',()=>{const d=discovery([],{ethereum:provider({providers:[provider({isMetaMask:true}),provider({isOkxWallet:true})]})});assert.equal(d.found.length,2);d.clean()});
test('repeated EIP6963 metadata deduplicates without numbered labels',()=>{const x=okx();const d=discovery([x]);d.announce({...x,provider:provider()});assert.equal(d.found.length,1);assert.equal(d.found[0].name,'OKX Wallet');d.clean()});
test('distinct announced UUIDs retain independently identifiable instances',()=>{const d=discovery([mm(),{...mm(),uuid:'independent-mm'}]);assert.equal(d.found.length,2);assert.notEqual(d.found[0].id,d.found[1].id);assert.deepEqual(d.found.map(x=>x.name),['MetaMask','MetaMask']);d.clean()});
test('selected provider remains bound through preparation despite late discovery',async()=>{const p=provider({isOkxWallet:true});const d=discovery([],{ethereum:p});const selected=d.found[0],w=new WalletSession();await w.connect(selected);const rev=w.revision;d.announce(okx(provider()));d.announce(mm());assert.equal(w.choice,selected);assert.equal(w.choice?.provider,p);await w.assertBinding(selected,w.account!,rev);assert.equal(d.found.length,2);d.clean()});
test('initial UI shows Connect without permanent brand selector',()=>{const d=discovery([mm(),okx()]);const html=renderToStaticMarkup(createElement(WalletPanel,{choices:d.found,wallet:new WalletSession(),onConnect:()=>{},onDisconnect:()=>{},disabled:false,text:copy.en}));assert.match(html,/>Connect Wallet</);assert.doesNotMatch(html,/<select|role="group"/);assert.match(html,/Verified during development/);d.clean()});
test('discovery requests no accounts and listener cleanup works',()=>{let calls=0;const p:Provider={request:async()=>{calls++;return []}};const d=discovery([mm(p)]);assert.equal(calls,0);d.clean();d.announce(okx());assert.equal(d.found.length,1)});

test('legacy OKX wrappers without announcements deduplicate by recognized identity',()=>{const d=discovery([],{okxwallet:provider({isOkxWallet:true}),ethereum:provider({isOKExWallet:true})});assert.equal(d.found.length,1);assert.equal(d.found[0].name,'OKX Wallet');d.clean()});
