import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {abi} from 'genlayer-js';
import {studionet} from 'genlayer-js/chains';
import {decodeFunctionData,fromRlp,hexToBytes} from 'viem';
import {WalletSession,FlowError,discoverWallets,type Provider} from '../src/wallet';
import {WriteController,newClientKey,type FlowState} from '../src/controller';
import {config,identifiers,normalizePack} from '../src/core';
import {createWriteAdapter,transactionOutcome,verifyTransactionBinding,type TxOutcome} from '../src/transactions';
import {AppError} from '../src/types';
const a=JSON.parse(fs.readFileSync(new URL('fixtures/synthetic.json',import.meta.url),'utf8'));
const tx='0x'+'a'.repeat(64) as `0x${string}`;
class FakeProvider implements Provider {isMetaMask?:boolean;isOkxWallet?:boolean;providers?:Provider[];account=a.creator;chain=61999;calls:string[]=[];failure?:string;events=new Map<string,(x:unknown)=>void>();async request(o:{method:string;params?:unknown[]}){this.calls.push(o.method);if(o.method===this.failure)throw {code:4001};if(o.method==='eth_accounts'||o.method==='eth_requestAccounts')return [this.account];if(o.method==='eth_chainId')return '0x'+this.chain.toString(16);if(o.method==='wallet_switchEthereumChain'){this.chain=61999;this.events.get('chainChanged')?.('0xf22f');return null}if(o.method==='eth_sendTransaction')return tx;return null}on(n:string,f:(x:unknown)=>void){this.events.set(n,f)}removeListener(n:string){this.events.delete(n)}}
async function setup(options:{found?:boolean;conflict?:boolean;receipts?:TxOutcome[];readLag?:number;readError?:boolean;protocolError?:boolean;submitError?:unknown;mutate?:boolean;returnMismatch?:boolean;record?:typeof a;accountChange?:boolean}={}){
 const data=options.record??a; const provider=new FakeProvider(),wallet=new WalletSession();const choice={id:'mock',name:'MetaMask',provider};await wallet.connect(choice);let writes=0,reads=0,lookups=0,n=0;const states:FlowState[]=[];const routes:string[]=[];let resolveWrite:()=>void=()=>{};
 const pending=new Promise<void>(r=>{resolveWrite=r});let started:()=>void=()=>{};const writeStarted=new Promise<void>(r=>{started=r});
 const good:TxOutcome={status:'FINALIZED',consensus:'MAJORITY_AGREE',execution:'SUCCESS',returns:[{request_id:data.request_id,disposition:'NEW',result_status:'PARTIAL'}],raw:{}};
 const controller=new WriteController(wallet,s=>states.push({...s}),{
 async getProtocolInfo(){if(options.protocolError)throw new AppError('CONFIGURATION_MISMATCH','Mismatch');return {}},
 async lookupRequest(){lookups++;if(options.accountChange)provider.events.get('accountsChanged')?.(['0x'+'1'.repeat(40)]);return options.found?{found:true,request_id:data.request_id,payload_digest:options.conflict?'f'.repeat(64):data.payload_digest,result_status:data.result_status}:{found:false,request_id:data.request_id}},
 async getAssessment(){reads++;if(options.readError)throw Error('RPC failure');if(options.readLag&&reads<=options.readLag)return {found:false};return {found:true,assessment:options.mutate?{...a,creator:'0x'+'0'.repeat(40)}:data}},
 },(_p,_creator,guard)=>({async assess(key,claim,context,urls){writes++;started();await guard();assert.deepEqual({key,claim,context,urls},{key:data.client_key,claim:data.claim,context:data.context,urls:data.urls});if(options.submitError)throw options.submitError;await pending;return tx},async getTransaction(){const r=options.receipts?.[n++]??good;const raw=Object.assign({hash:tx,sender:data.creator,recipient:config.contract,data:{calldata:{base64:Buffer.from(abi.calldata.encode(abi.calldata.makeCalldataObject('assess',[data.client_key,data.claim,data.context,data.urls]))).toString('base64')}}},r.raw);r.raw=raw;return options.returnMismatch?{...r,returns:[{request_id:'f'.repeat(64),disposition:'NEW',result_status:'PARTIAL'}]}:r}}),async()=>{},id=>routes.push(id));
 return {provider,wallet,controller,states,routes,get writes(){return writes},get reads(){return reads},get lookups(){return lookups},resolveWrite,writeStarted,draft:{client_key:data.client_key,claim:data.claim,context:data.context,urls:data.urls}};
}
test('provider discovery selects explicit MetaMask/OKX among multiple legacy providers without connect',()=>{const m=new FakeProvider();m.isMetaMask=true;const o=new FakeProvider();o.isOkxWallet=true;const target=Object.assign(new EventTarget(),{ethereum:{providers:[m,o]},okxwallet:o});let found:any[]=[];const clean=discoverWallets(target as any,x=>found=x);assert.deepEqual(found.map(x=>x.name),['OKX Wallet','MetaMask']);assert.equal(found[1].provider,m);assert.equal(found[0].provider,o);assert.equal(m.calls.length+o.calls.length,0);clean()});
test('EIP6963 announcement prefers explicit rdns and deduplicates provider identity',()=>{const target=new EventTarget();const provider=new FakeProvider();let found:any[]=[];target.addEventListener('eip6963:requestProvider',()=>target.dispatchEvent(new CustomEvent('eip6963:announceProvider',{detail:{info:{rdns:'io.metamask',uuid:'mm',name:'MetaMask'},provider}})));const clean=discoverWallets(target as any,x=>found=x);assert.equal(found.length,1);assert.equal(found[0].provider,provider);clean()});
test('connect rejection is classified; listeners cleaned and local detach does not revoke authorization',async()=>{const p=new FakeProvider();p.failure='eth_requestAccounts';const w=new WalletSession();await assert.rejects(()=>w.connect({id:'m',name:'MetaMask',provider:p}),(e:FlowError)=>e.code==='USER_REJECTED_CONNECT');assert.equal(p.events.size,0);assert.equal(w.account,undefined);assert.ok(!p.calls.includes('wallet_revokePermissions'))});
test('wrong chain switches using Stable parameters, switch rejection sends nothing',async()=>{const p=new FakeProvider(),w=new WalletSession();await w.connect({id:'o',name:'OKX Wallet',provider:p});p.chain=1;await w.ensureNetwork();assert.equal(p.chain,61999);p.chain=1;p.failure='wallet_switchEthereumChain';await assert.rejects(()=>w.ensureNetwork(),(e:FlowError)=>e.code==='USER_REJECTED_NETWORK_SWITCH');assert.ok(!p.calls.includes('eth_sendTransaction'))});
test('missing network follows add then switch, with locked native currency/RPC',async()=>{const p=new FakeProvider(),original=p.request.bind(p);let first=true;const params:any[]=[];p.request=async o=>{params.push(o);if(o.method==='wallet_switchEthereumChain'&&first){first=false;throw {code:4902}}return original(o)};const w=new WalletSession();await w.connect({id:'m',name:'MetaMask',provider:p});p.chain=1;await w.ensureNetwork();const add=params.find(x=>x.method==='wallet_addEthereumChain').params[0];assert.equal(add.chainId,'0xf22f');assert.deepEqual(add.rpcUrls,[config.rpc]);assert.deepEqual(add.nativeCurrency,studionet.nativeCurrency)});
test('account/chain events invalidate preparation; disconnect only detaches UI',async()=>{const p=new FakeProvider(),w=new WalletSession(),c={id:'m',name:'MetaMask',provider:p};await w.connect(c);const revision=w.revision;p.events.get('accountsChanged')?.(['0x'+'1'.repeat(40)]);await assert.rejects(()=>w.assertBinding(c,a.creator,revision),(e:FlowError)=>e.code==='ACCOUNT_CHANGED_BEFORE_SEND');w.disconnect();assert.equal(p.events.size,0);assert.equal(w.account,undefined)});
test('account changed without event and incorrect chain are checked before signature',async()=>{const x=await setup(),choice=x.wallet.choice!,rev=x.wallet.revision;x.provider.account='0x'+'1'.repeat(40);await assert.rejects(()=>x.wallet.assertBinding(choice,a.creator,rev));x.provider.account=a.creator;x.provider.chain=1;await assert.rejects(()=>x.wallet.assertBinding(choice,a.creator,rev),(e:FlowError)=>e.code==='WRONG_NETWORK')});
test('frozen reference vectors retain TS input/hash parity',async()=>{const vectors=JSON.parse(fs.readFileSync(new URL('fixtures/canonical-vectors.json',import.meta.url),'utf8'));for(const v of vectors){const p=normalizePack(v.raw_inputs.claim,v.raw_inputs.context,v.raw_inputs.urls);assert.deepEqual(await identifiers(v.creator,v.raw_inputs.client_key,p),{request_id:v.request_id,payload_digest:v.payload_digest})}});
test('client_key valid and retained across preparation/reconnect; explicit new alone creates new key',async()=>{const x=await setup();const key=newClientKey();assert.match(key,/^[A-Za-z0-9_-]{1,64}$/);await x.wallet.connect(x.wallet.choice!);assert.equal(x.draft.client_key,a.client_key);assert.notEqual(x.controller.newAssessment(),key)});
test('preflight existing same payload opens finalized record, no new write',async()=>{const x=await setup({found:true});await x.controller.submit(x.draft);assert.equal(x.writes,0);assert.deepEqual(x.routes,[a.request_id]);assert.equal(x.controller.snapshot.state,'finalized_partial')});
test('preflight conflicting payload rejects before any write',async()=>{const x=await setup({found:true,conflict:true});await x.controller.submit(x.draft);assert.equal(x.writes,0);assert.equal(x.controller.snapshot.error?.code,'IDEMPOTENCY_CONFLICT')});
test('single controller locks double click, submitted real ID retained and finalized read routes report',async()=>{const x=await setup();const first=x.controller.submit(x.draft);await x.writeStarted;assert.equal(x.writes,1);await x.controller.submit(x.draft);assert.equal(x.writes,1);x.resolveWrite();await first;assert.ok(x.states.some(s=>s.state==='submitted'&&s.tx===tx));assert.equal(x.controller.snapshot.state,'finalized_partial');assert.equal(x.controller.snapshot.prepared?.request_id,a.request_id);assert.deepEqual(x.routes,[a.request_id]);await x.controller.submit(x.draft);assert.equal(x.writes,1)});
test('signature rejection keeps same draft key and exposes recoverable rejection',async()=>{const x=await setup({submitError:{code:4001}});await x.controller.submit(x.draft);assert.equal(x.controller.snapshot.error?.code,'USER_REJECTED_SIGNATURE');assert.equal(x.controller.snapshot.state,'rejected_by_user');assert.equal(x.controller.snapshot.prepared?.client_key,a.client_key);assert.equal(x.controller.locked,false)});
test('ACCEPTED is never final success and causes no assessment read until FINALIZED',async()=>{const x=await setup({receipts:[{status:'ACCEPTED',raw:{}},{status:'FINALIZED',execution:'SUCCESS',consensus:'MAJORITY_AGREE',returns:[{request_id:a.request_id,disposition:'NEW',result_status:'PARTIAL'}],raw:{}}]});x.resolveWrite();await x.controller.submit(x.draft);assert.ok(x.states.some(s=>s.state==='accepted_waiting_finality'&&!s.assessment));assert.equal(x.reads,1)});
for(const r of [{status:'FINALIZED',execution:'ERROR'},{status:'FINALIZED',execution:'SUCCESS',consensus:'MAJORITY_DISAGREE'},{status:'FINALIZED'}] as TxOutcome[])test('finalized failure does not read a successful report '+JSON.stringify(r),async()=>{const x=await setup({receipts:[{...r,raw:{}}]});x.resolveWrite();await x.controller.submit(x.draft);assert.equal(x.routes.length,0);assert.equal(x.reads,0);assert.equal(x.controller.snapshot.error?.code,'TRANSACTION_EXECUTION_FAILED');assert.equal(x.controller.snapshot.state,'execution_failed')});
test('finalized read lag stays reading, retries only read and does not resend',async()=>{const x=await setup({readLag:2});x.resolveWrite();await x.controller.submit(x.draft);assert.equal(x.reads,3);assert.equal(x.writes,1);assert.deepEqual(x.routes,[a.request_id])});
test('receipt request_id mismatch fails before read',async()=>{const x=await setup({returnMismatch:true});x.resolveWrite();await x.controller.submit(x.draft);assert.equal(x.reads,0);assert.equal(x.controller.snapshot.error?.code,'REQUEST_ID_MISMATCH');assert.equal(x.routes.length,0)});
test('finalized record input/account mismatch cannot produce success',async()=>{const x=await setup({mutate:true});x.resolveWrite();await x.controller.submit(x.draft);assert.equal(x.controller.snapshot.error?.code,'REQUEST_ID_MISMATCH');assert.equal(x.routes.length,0)});
test('transport read error preserves transaction and never resends',async()=>{const x=await setup({readError:true});x.resolveWrite();await x.controller.submit(x.draft);assert.equal(x.controller.snapshot.error?.code,'RPC_READ_FAILED');assert.equal(x.controller.snapshot.state,'tracking_unavailable');assert.equal(x.controller.snapshot.tx,tx);assert.equal(x.writes,1)});
test('protocol mismatch stops before lookup and signature',async()=>{const x=await setup({protocolError:true});await x.controller.submit(x.draft);assert.equal(x.lookups,0);assert.equal(x.writes,0);assert.equal(x.controller.snapshot.error?.code,'PROTOCOL_MISMATCH')});
test('confirmed insufficient funds classified; unknown submission locks automatic resubmission',async()=>{for(const error of [Error('insufficient funds for gas'),{code:-32000,message:'insufficient funds for gas'},Error('response lost')]){const x=await setup({submitError:error});await x.controller.submit(x.draft);assert.equal(x.controller.snapshot.error?.code,error.message.includes('insufficient')?'INSUFFICIENT_TEST_GEN':'TRANSACTION_SUBMISSION_FAILED');await x.controller.submit(x.draft);assert.equal(x.writes,1)}});
test('locked SDK wallet path encodes canonical assess, full consensus and fee estimate before signature (MOCK)',async()=>{const original=globalThis.fetch,p=new FakeProvider();let encoded:any,estimates=0,guards=0;p.request=async o=>{assert.equal(o.method,'eth_sendTransaction');encoded=o.params?.[0];return tx};globalThis.fetch=async(_url,o)=>{const q=JSON.parse(o?.body as string);const result=q.method==='eth_getTransactionCount'?'0x1':q.method==='eth_estimateGas'?(estimates++,'0x7a120'):'0x0';return new Response(JSON.stringify({jsonrpc:'2.0',id:q.id,result}))};try{const w=createWriteAdapter(p,a.creator,async()=>{guards++});assert.equal(await w.assess(a.client_key,a.claim,a.context,a.urls),tx);assert.equal(estimates,2);assert.ok(guards>=3);assert.equal(encoded.chainId,'0xf22f');assert.equal(encoded.gas,'0x7a120');const decoded=decodeFunctionData({abi:studionet.consensusMainContract!.abi,data:encoded.data});assert.equal(decoded.functionName,'addTransaction');const args=decoded.args as any[];assert.equal(args[1].toLowerCase(),config.contract.toLowerCase());assert.equal(args[2],5n);assert.equal(args[3],3n);const data=fromRlp(args[4],'hex') as string[];assert.equal(data[1],'0x00');const call=abi.calldata.decode(hexToBytes(data[0])) as Map<string,unknown>;assert.equal(call.get('method'),'assess')}finally{globalThis.fetch=original}});
test('SDK estimate failure cannot reach wallet signing even if SDK fallback triggers (MOCK)',async()=>{const original=globalThis.fetch,p=new FakeProvider();globalThis.fetch=async(_url,o)=>{const q=JSON.parse(o?.body as string);return new Response(JSON.stringify(q.method==='eth_estimateGas'?{error:{code:-1,message:'estimate unavailable'}}:{result:'0x0'}))};try{await assert.rejects(()=>createWriteAdapter(p,a.creator,async()=>{}).assess(a.client_key,a.claim,a.context,a.urls));assert.ok(!p.calls.includes('eth_sendTransaction'))}finally{globalThis.fetch=original}});
test('actual historical receipt decoder uses official calldata encoding, no guessed result text',()=>{const raw=JSON.parse(fs.readFileSync(new URL('fixtures/receipt-summary.json',import.meta.url),'utf8'));const out=transactionOutcome(raw);assert.equal(out.status,'FINALIZED');assert.equal(out.execution,'SUCCESS');assert.equal(out.consensus,'MAJORITY_AGREE');assert.ok(out.returns?.every(r=>r.request_id===a.request_id));assert.ok(out.returns?.length)});

test('finalized COMPLETE maps only after matched public-document record',async()=>{const record=JSON.parse(fs.readFileSync(new URL('fixtures/public-document.json',import.meta.url),'utf8'));const x=await setup({record});x.resolveWrite();await x.controller.submit(x.draft);assert.equal(x.controller.snapshot.state,'finalized_complete');assert.deepEqual(x.routes,[record.request_id])});

test('account change during preflight cancels write preparation before signature',async()=>{const x=await setup({accountChange:true});await x.controller.submit(x.draft);assert.equal(x.writes,0);assert.equal(x.controller.snapshot.error?.code,'ACCOUNT_CHANGED_BEFORE_SEND');assert.equal(x.controller.locked,false)});
test('exhausted finalized read lag pauses tracking and never resends or claims success',async()=>{const x=await setup({readLag:20});x.resolveWrite();await x.controller.submit(x.draft);assert.equal(x.reads,6);assert.equal(x.writes,1);assert.equal(x.routes.length,0);assert.equal(x.controller.snapshot.state,'tracking_unavailable')});

test('receipt binding matches actual historical assess and rejects foreign hash/sender/contract/calldata',()=>{const raw=JSON.parse(fs.readFileSync(new URL('fixtures/receipt-summary.json',import.meta.url),'utf8'));const p={...a,contract:config.contract};verifyTransactionBinding(raw,raw.hash,p);for(const bad of [{...raw,hash:tx},{...raw,sender:'0x'+'1'.repeat(40)},{...raw,recipient:'0x'+'1'.repeat(40)},{...raw,data:{calldata:'bm90IGNhbGxkYXRh'}}])assert.throws(()=>verifyTransactionBinding(bad,raw.hash,p),(e:FlowError)=>e.code==='REQUEST_ID_MISMATCH')});
