import React,{useEffect,useState} from 'react';
import {config,demos,codepoints,normalizePack,parseRoute,matrix} from './core';
import {RecoveryStore,browserStorage} from './recovery';
import {type ReadIssue} from './read-scheduler';
import {adapter} from './genlayer';
import {copy,type Language} from './i18n';
import {AppError,type Assessment,type AssessmentResult} from './types';
import {WalletPanel} from './WalletPanel';
import {discoverWallets,WalletSession,FlowError,type WalletChoice} from './wallet';
import {WriteController,newClientKey,type Draft,type FlowState} from './controller';
import {type LifecycleState} from './lifecycle';
type Text=(typeof copy)[Language];
export function Matrix({assessment,text=copy.en}:{assessment:Assessment;text?:Text}){const rows=matrix(assessment);return <div className="table-wrap"><table className="matrix"><caption>{text.matrixCaption}</caption><thead><tr><th aria-label="Source"/>{rows.map((_,i)=><th key={i}>{String.fromCharCode(65+i)}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i}><th>{String.fromCharCode(65+i)}</th>{row.map((cell,j)=><td key={j} className={cell.toLowerCase()}>{cell}</td>)}</tr>)}</tbody></table></div>}
export function Progress({state='idle',text=copy.en,flow,resume}:{state?:LifecycleState;text?:Text;flow?:FlowState;resume?:()=>void}){return <section className="panel"><p className="eyebrow">{text.progress}</p><h1>{text[state]}</h1><p>{flow?text.progressLive:text.progressDisabled}</p><code>{state}</code>{flow?.receipt&&<dl><dt>{text.network}</dt><dd>{flow.receipt.status}</dd><dt>Consensus</dt><dd>{flow.receipt.consensus??'—'}</dd><dt>Execution</dt><dd>{flow.receipt.execution??'—'}</dd></dl>}{flow?.tx&&<><p className="mono">{flow.tx}</p><a href={`${config.explorer}/tx/${flow.tx}`} target="_blank" rel="noreferrer">Explorer · {config.network}</a><p>{text.pendingHelp}</p></>}{flow?.prepared&&<p className="mono">{text.request}: {flow.prepared.request_id}</p>}{flow?.readIssue&&<p role="status">{text[flow.readIssue]} <code>{flow.readIssue}</code></p>}{flow?.prepared&&<small>{text.key}: <code>{flow.prepared.client_key}</code></small>}{flow?.error&&<p role="alert">{text[flow.error.code]} <code>{flow.error.code}</code></p>}{state==='tracking_unavailable'&&<button onClick={resume}>{text.resume}</button>}{flow?.error?.code==='INSUFFICIENT_TEST_GEN'&&<p><a href="https://studio.genlayer.com/" target="_blank" rel="noreferrer">{text.faucet}</a> · {text.faucetHelp}</p>}</section>}
export function Report({assessment:a,text=copy.en}:{assessment:Assessment;text?:Text}){const demo=demos.find(d=>d.request_id===a.request_id);return <>
 <section className="panel"><p className="eyebrow">{text.readOnly}</p>{demo&&<span className="badge">{demo.label==='SYNTHETIC DEMO'?text.synthetic:text.real}</span>}<h1>{a.claim}</h1>{a.context&&<p className="context">{a.context}</p>}<p>{text.notTruth}</p><div className="facts"><div><span>{text.result}</span><strong>{a.result_status}</strong></div><div><span>{text.max}</span><strong>{a.max_supported_independent_set.map(i=>String.fromCharCode(65+i)).join(', ')||'—'}</strong><small>{text.size}: {a.max_supported_independent_set_size}</small></div><div><span>{text.counts}</span><strong>{a.dependent_pair_count} DEPENDENT · {a.independent_pair_count} INDEPENDENT · {a.unknown_pair_count} UNKNOWN</strong></div></div><p>{text.partialHelp}</p></section>
 <section className="panel"><h2>{text.matrix}</h2><Matrix assessment={a} text={text}/><dl className="legend"><dt>DEPENDENT</dt><dd>{text.dependent}</dd><dt>INDEPENDENT</dt><dd>{text.independent}</dd><dt>UNKNOWN</dt><dd>{text.unknown}</dd></dl><p>{text.maxHelp}</p></section>
 <section className="panel"><h2>{text.sources}</h2>{a.sources.map(s=><article className="source" key={s.index}><h3>{String.fromCharCode(65+s.index)} · {text.sources} {s.index}</h3><a href={s.url} target="_blank" rel="noreferrer">{s.url}</a><dl><dt>{text.status}</dt><dd>{s.read_status}</dd><dt>{text.relevance}</dt><dd>{s.relevance}</dd><dt>{text.digest}</dt><dd className="mono">{s.content_digest??'—'}</dd></dl></article>)}</section>
 <section className="panel"><h2>{text.finalSnapshot}</h2><dl><dt>{text.creator}</dt><dd className="mono">{a.creator}</dd><dt>{text.protocol}</dt><dd>{a.protocol_version}</dd><dt>{text.request}</dt><dd className="mono">{a.request_id}</dd><dt>{text.payload}</dt><dd className="mono">{a.payload_digest}</dd><dt>{text.contract}</dt><dd className="mono">{config.contract}</dd></dl>{demo&&<p><a href={`${config.explorer}/tx/${demo.creation_transaction}`} target="_blank" rel="noreferrer">{text.creation}</a></p>}<label>{text.share}<input readOnly value={typeof window==='undefined'?`#/report/${a.request_id}`:`${window.location.href.split('#')[0]}#/report/${a.request_id}`}/></label><small>{text.shareHelp}</small></section></>}
function EvidencePack({text,draft,setDraft,onSubmit,onNew,ready,locked,active}:{text:Text;draft:Draft;setDraft:(d:Draft)=>void;onSubmit:()=>void;onNew:()=>void;ready:boolean;locked:boolean;active:boolean}){const {claim,context,urls}=draft;const setClaim=(claim:string)=>setDraft({...draft,claim});const setContext=(context:string)=>setDraft({...draft,context});const setUrls=(urls:string[])=>setDraft({...draft,urls});let error='';if(claim||context||urls.some(Boolean)){try{normalizePack(claim,context,urls)}catch(e){error=e instanceof Error?e.message:'Invalid input'}}return <>
 <section className="hero"><p className="eyebrow">{text.tag}</p><h1>{text.headline}</h1><p className="intro">{text.intro}</p><p>{text.why}</p><div className="examples">{demos.map((d,i)=><a className={i===0?'button':'button secondary'} key={d.request_id} href={`#/report/${d.request_id}`}>{i===0?text.example:text.realExample}<small>{i===0?text.synthetic:text.real}</small></a>)}</div><p className="notice">{text.notTruth}</p></section>
 <section className="panel"><h2>{text.start}</h2><label>{text.claim}<textarea disabled={locked} value={claim} onChange={e=>setClaim(e.target.value)} rows={3}/><small>{codepoints(claim)} / {config.limits.claim} {text.limits}</small></label><label>{text.context}<textarea disabled={locked} value={context} onChange={e=>setContext(e.target.value)} rows={2}/><small>{codepoints(context)} / {config.limits.context} {text.limits}</small></label><h3>{text.sources}</h3>{urls.map((url,i)=><div className="url-row" key={i}><label>{String.fromCharCode(65+i)}<input disabled={locked} value={url} onChange={e=>setUrls(urls.map((u,j)=>j===i?e.target.value:u))} placeholder="https://raw.githubusercontent.com/…/source.txt" aria-label={`${text.sourceUrl} ${i+1}`}/></label>{urls.length>2&&<button className="small" disabled={locked} onClick={()=>setUrls(urls.filter((_,j)=>i!==j))}>{text.remove}</button>}</div>)}{urls.length<4&&<button className="secondary small" disabled={locked} onClick={()=>setUrls([...urls,''])}>{text.add}</button>}<p>{text.scope}</p><small>URL ≤ {config.limits.url_bytes} ASCII bytes · {text.sourceLimit} ≤ {config.limits.body_bytes} bytes / {config.limits.text_codepoints} code points</small>{error&&<p role="status" className="notice">{text.invalidInput}: {error}</p>}<p><button disabled={!ready||locked||Boolean(error)||!claim||urls.some(x=>!x)} onClick={onSubmit}>{text.assess}</button> <button className="secondary" disabled={active} onClick={onNew}>{text.newAssessment}</button></p><p>{ready?text.submissionHelp:text.disabled}</p><small>{text.key}: <code>{draft.client_key}</code></small></section></>}
export default function App(){const [language,setLanguage]=useState<Language>('en'),[route,setRoute]=useState(()=>parseRoute(window.location.hash));const [data,setData]=useState<AssessmentResult|undefined>(),[error,setError]=useState<AppError>(),[loading,setLoading]=useState(false);const text=copy[language];
 const [,walletRefresh]=useState(0),[choices,setChoices]=useState<WalletChoice[]>([]),[walletError,setWalletError]=useState<FlowError>(),[connecting,setConnecting]=useState(false);
 const [store]=useState(()=>new RecoveryStore(browserStorage()));const [saved]=useState(()=>store.load());const [readAttempt,setReadAttempt]=useState(0);
 const [wallet]=useState(()=>new WalletSession(()=>walletRefresh(x=>x+1)));const [flow,setFlow]=useState<FlowState>({state:'idle'});const [controller]=useState(()=>new WriteController(wallet,setFlow,undefined,undefined,undefined,undefined,{store,blocked:store.problem==='INVALID_RECOVERY_STATE'}));const [draft,setDraft]=useState<Draft>(()=>saved?.draft??({client_key:newClientKey(),claim:'',context:'',urls:['','']}));
 useEffect(()=>{const cleanup=discoverWallets(window,setChoices);return ()=>{cleanup();wallet.disconnect();controller.stop()}},[wallet,controller]);
 useEffect(()=>{if(saved?.active){if(window.location.hash.indexOf('/report/')<0)window.location.hash='/progress';void controller.recover(saved.active)}},[controller,saved]);
 useEffect(()=>{if(!controller.locked){const before=store.available+'|'+store.problem;store.save(draft);if(before!==store.available+'|'+store.problem)walletRefresh(n=>n+1)}},[draft,controller,store]);
 async function connect(choice:WalletChoice){if(connecting)return;setConnecting(true);setWalletError(undefined);if(!controller.snapshot.tx&&!controller.locked)setFlow({state:'requesting_wallet'});try{await wallet.connect(choice);if(!controller.snapshot.tx&&!controller.locked)setFlow({state:'idle'})}catch(e){setWalletError(e as FlowError);if(!controller.snapshot.tx&&!controller.locked)setFlow({state:'rejected_by_user'})}finally{setConnecting(false)}}
 function submit(){if(controller.locked)return;window.location.hash='/progress';void controller.submit(draft)}
 function fresh(){try{const key=controller.newAssessment();setDraft({client_key:key,claim:'',context:'',urls:['','']});window.location.hash='/'}catch{}}
 useEffect(()=>{const change=()=>setRoute(parseRoute(window.location.hash));window.addEventListener('hashchange',change);return ()=>window.removeEventListener('hashchange',change)},[]);
 useEffect(()=>{if(saved?.active&&route.view!=='report'){setLoading(false);return}let cancelled=false;setData(undefined);setError(undefined);setLoading(true);const work=route.view==='report'?adapter.getAssessment(route.request!):adapter.getProtocolInfo();work.then(x=>{if(!cancelled&&'found' in x)setData(x as AssessmentResult)}).catch(e=>{if(!cancelled)setError(e instanceof AppError?e:new AppError('TRANSPORT_ERROR',String(e)))}).finally(()=>{if(!cancelled)setLoading(false)});return ()=>{cancelled=true}},[route.view,route.request,readAttempt,saved]);
 const issue=(error as AppError & {readIssue?:ReadIssue})?.readIssue;const message=issue?text[issue]:error?.kind==='CONFIGURATION_MISMATCH'?text.mismatch:error?.kind==='ONCHAIN_DATA_CONSISTENCY_ERROR'?text.consistency:error?.kind==='INVALID_INPUT'?text.invalidInput:text.transport;
 return <><header><a className="brand" href="#/">EchoMap<span>↗</span></a><nav><a href="#/">{text.start}</a><a href="#/progress">{text.progress}</a><button className="language" onClick={()=>setLanguage(language==='en'?'zh':'en')}>{language==='en'?'中文':'English'}</button></nav></header><main><div className="network"><span>{text.network}: {config.network} · {config.chainId}</span><span>{text.contract}: <code>{config.contract}</code></span></div>{(!store.available||store.problem)&&<p role="alert">{store.problem==='INVALID_RECOVERY_STATE'?text.invalidRecovery:text.storageUnavailable}</p>}{error?<section className="panel error" role="alert"><h1>{message}</h1><details><summary>{text.errorDetail}</summary>{error.message}</details><button className="secondary" onClick={()=>setReadAttempt(n=>n+1)}>{text.resume}</button></section>:route.view==='invalid'?<section className="panel"><h1>{text.invalidRoute}</h1></section>:route.view==='start'?<><WalletPanel choices={choices} wallet={wallet} onConnect={choice=>{void connect(choice)}} onDisconnect={()=>wallet.disconnect()} disabled={connecting||(controller.active&&!flow.tx)} text={text}/>{walletError&&<p role="alert">{text[walletError.code]} <code>{walletError.code}</code></p>}<EvidencePack text={text} draft={draft} setDraft={setDraft} onSubmit={submit} onNew={fresh} ready={Boolean(wallet.account)} locked={controller.locked} active={!controller.canStartNew}/></>:route.view==='progress'?<><Progress text={text} state={flow.state} flow={flow} resume={()=>{void controller.resume()}}/><button className="secondary" disabled={!controller.canStartNew} onClick={fresh}>{text.newAssessment}</button></>:loading?<section className="panel" role="status">{text.loading}</section>:data?.found?<Report assessment={data.assessment} text={text}/>:<section className="panel"><h1>{text.notFound}</h1></section>}</main><footer>{text.notTruth} · GenLayer Stable Studionet</footer></>;
}
